#!/bin/bash
PATH_TO_PRESENTATION_MANAGER=~/slideman

git clone https://github.com/deralex/slideman $PATH_TO_PRESENTATION_MANAGER

rm -r "${PATH_TO_PRESENTATION_MANAGER}/static/slides"
cp -r . "${PATH_TO_PRESENTATION_MANAGER}/static/"
mv ${PATH_TO_PRESENTATION_MANAGER}/static/*.css "${PATH_TO_PRESENTATION_MANAGER}/static/css/theme"

cd "${PATH_TO_PRESENTATION_MANAGER}"
cargo build
mv target/debug/slideman ./slideman
