#!/bin/bash
PATH_TO_PRESENTATION_MANAGER=~/slideman

cp -r * "${PATH_TO_PRESENTATION_MANAGER}/static/"
mv ${PATH_TO_PRESENTATION_MANAGER}/static/*.css "${PATH_TO_PRESENTATION_MANAGER}/static/css/theme"
rm -r ${PATH_TO_PRESENTATION_MANAGER}/static/templates
